package chatsocket;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;

/**
 * @author edilson-silva
 */
public class ClientChat extends javax.swing.JFrame {

    static Socket clientSocket;
    static DataInputStream messageInput;
    static DataOutputStream messageOutput;

    public ClientChat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MessagesDisplayScrollPanelClient = new javax.swing.JScrollPane();
        MessagesDisplayClient = new javax.swing.JTextArea();
        MessageInputClient = new javax.swing.JTextField();
        SendButtonClient = new javax.swing.JButton();
        nameLabelClient = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MessagesDisplayClient.setColumns(20);
        MessagesDisplayClient.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        MessagesDisplayClient.setRows(5);
        MessagesDisplayScrollPanelClient.setViewportView(MessagesDisplayClient);

        MessageInputClient.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        SendButtonClient.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SendButtonClient.setText("Enviar");
        SendButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonClientActionPerformed(evt);
            }
        });

        nameLabelClient.setText("CLIENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MessagesDisplayScrollPanelClient, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MessageInputClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SendButtonClient))
                    .addComponent(nameLabelClient))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabelClient, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MessagesDisplayScrollPanelClient, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MessageInputClient)
                    .addComponent(SendButtonClient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonClientActionPerformed
        try {
            String messageOutData = MessageInputClient.getText().trim();
            messageOutput.writeUTF(messageOutData);
        } catch (IOException e) { }
    }//GEN-LAST:event_SendButtonClientActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientChat().setVisible(true);
            }
        });
        
        String messageInputData = "";
        
        try {
            clientSocket = new Socket("127.0.0.1", 5019);
            
            messageInput = new DataInputStream(clientSocket.getInputStream());
            messageOutput = new DataOutputStream(clientSocket.getOutputStream());
            
            while (!messageInputData.equals("sair")){
                messageInputData = messageInput.readUTF();
                MessagesDisplayClient.setText(MessagesDisplayClient.getText().trim() + "\n" + messageInputData);
            }            
        } catch (IOException e) { }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField MessageInputClient;
    private static javax.swing.JTextArea MessagesDisplayClient;
    private javax.swing.JScrollPane MessagesDisplayScrollPanelClient;
    private static javax.swing.JButton SendButtonClient;
    private javax.swing.JLabel nameLabelClient;
    // End of variables declaration//GEN-END:variables
}
